name: Continuous Integration and Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Normalize repo name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/app" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image for cache
        run: docker pull $IMAGE:latest || true

      - name: Build Image
        run: docker build --cache-from $IMAGE:latest -t $IMAGE:latest -f ./Dockerfile .

      - name: Push image
        run: docker push $IMAGE:latest